# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# This re-usable component runs a test

name: test-cover-lint

on:
  # run on call (trigger event), dispatch (manual) and push to tag
  workflow_call:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    tags:
      - v*

jobs:

  test-and-cover:
    name: test-component
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4 # needed for cache
      - name: set up go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: test
        run: make test
      - name: coverage
        run: make coverage-ok

  golangci:
    name: lint-component
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5 
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        # https://github.com/golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57 # can use "latest"
